/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeue extends Token
{
    public TMeue()
    {
        super.setText("e");
    }

    public TMeue(int line, int pos)
    {
        super.setText("e");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeue(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeue(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeue text.");
    }
}
