/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeufimSe extends Token
{
    public TMeufimSe()
    {
        super.setText("fim se");
    }

    public TMeufimSe(int line, int pos)
    {
        super.setText("fim se");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeufimSe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeufimSe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeufimSe text.");
    }
}
