/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeunao extends Token
{
    public TMeunao()
    {
        super.setText("nao");
    }

    public TMeunao(int line, int pos)
    {
        super.setText("nao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeunao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeunao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeunao text.");
    }
}
