/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeufimRepita extends Token
{
    public TMeufimRepita()
    {
        super.setText("fim repita");
    }

    public TMeufimRepita(int line, int pos)
    {
        super.setText("fim repita");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeufimRepita(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeufimRepita(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeufimRepita text.");
    }
}
