/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TUltimofim extends Token
{
    public TUltimofim()
    {
        super.setText("fim.");
    }

    public TUltimofim(int line, int pos)
    {
        super.setText("fim.");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUltimofim(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUltimofim(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUltimofim text.");
    }
}
