/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeutipo extends Token
{
    public TMeutipo()
    {
        super.setText("tipo");
    }

    public TMeutipo(int line, int pos)
    {
        super.setText("tipo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeutipo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeutipo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeutipo text.");
    }
}
