/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeufimPara extends Token
{
    public TMeufimPara()
    {
        super.setText("fim para");
    }

    public TMeufimPara(int line, int pos)
    {
        super.setText("fim para");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeufimPara(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeufimPara(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeufimPara text.");
    }
}
