/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeucomentarioLinha extends Token
{
    public TMeucomentarioLinha(String text)
    {
        setText(text);
    }

    public TMeucomentarioLinha(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeucomentarioLinha(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeucomentarioLinha(this);
    }
}
