/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeude extends Token
{
    public TMeude()
    {
        super.setText("de");
    }

    public TMeude(int line, int pos)
    {
        super.setText("de");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeude(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeude(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeude text.");
    }
}
