/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.node;

import meuprojetoLFT.analysis.*;

@SuppressWarnings("nls")
public final class TMeurepita extends Token
{
    public TMeurepita()
    {
        super.setText("repita");
    }

    public TMeurepita(int line, int pos)
    {
        super.setText("repita");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMeurepita(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMeurepita(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMeurepita text.");
    }
}
