/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.analysis;

import meuprojetoLFT.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTMeuprograma(TMeuprograma node);
    void caseTMeuleia(TMeuleia node);
    void caseTMeuescreva(TMeuescreva node);
    void caseTMeufim(TMeufim node);
    void caseTMeuultimofim(TMeuultimofim node);
    void caseTMeufaca(TMeufaca node);
    void caseTMeude(TMeude node);
    void caseTMeuate(TMeuate node);
    void caseTMeuenquanto(TMeuenquanto node);
    void caseTMeupasso(TMeupasso node);
    void caseTMeupara(TMeupara node);
    void caseTMeurepita(TMeurepita node);
    void caseTMeuvariavel(TMeuvariavel node);
    void caseTMeuinicio(TMeuinicio node);
    void caseTMeutipo(TMeutipo node);
    void caseTMeuregistro(TMeuregistro node);
    void caseTMeureal(TMeureal node);
    void caseTMeuinteiro(TMeuinteiro node);
    void caseTMeucaractere(TMeucaractere node);
    void caseTMeuse(TMeuse node);
    void caseTMeuentao(TMeuentao node);
    void caseTMeusenao(TMeusenao node);
    void caseTMeucaso(TMeucaso node);
    void caseTMeuavalie(TMeuavalie node);
    void caseTMeufimavalie(TMeufimavalie node);
    void caseTMeufimSe(TMeufimSe node);
    void caseTMeufimPara(TMeufimPara node);
    void caseTMeufimEnquanto(TMeufimEnquanto node);
    void caseTMeufimRepita(TMeufimRepita node);
    void caseTMeusnumeros(TMeusnumeros node);
    void caseTMeuatribuicao(TMeuatribuicao node);
    void caseTMeufimLinha(TMeufimLinha node);
    void caseTMeuParentEsq(TMeuParentEsq node);
    void caseTMeuParentDir(TMeuParentDir node);
    void caseTMeuColcheEsq(TMeuColcheEsq node);
    void caseTMeuColcheDir(TMeuColcheDir node);
    void caseTMeuvirgula(TMeuvirgula node);
    void caseTMeupontos(TMeupontos node);
    void caseTMeusmais(TMeusmais node);
    void caseTMeusmenos(TMeusmenos node);
    void caseTMeumultiplicacao(TMeumultiplicacao node);
    void caseTMeusdivisao(TMeusdivisao node);
    void caseTMeumenorque(TMeumenorque node);
    void caseTMeumenorigual(TMeumenorigual node);
    void caseTMeumaiorque(TMeumaiorque node);
    void caseTMeumaiorigual(TMeumaiorigual node);
    void caseTMeuigual(TMeuigual node);
    void caseTMeunao(TMeunao node);
    void caseTMeue(TMeue node);
    void caseTMeuou(TMeuou node);
    void caseTMeuxor(TMeuxor node);
    void caseTMeuconstante(TMeuconstante node);
    void caseTMinhaaspassimples(TMinhaaspassimples node);
    void caseTMeuespacoembranco(TMeuespacoembranco node);
    void caseTMeuidentificador(TMeuidentificador node);
    void caseTMeucomentarioLinha(TMeucomentarioLinha node);
    void caseTComentario(TComentario node);
    void caseTComentarioFim(TComentarioFim node);
    void caseTComentarioCorpo(TComentarioCorpo node);
    void caseTBarra(TBarra node);
    void caseTEstrela(TEstrela node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
