/* This file was generated by SableCC (http://www.sablecc.org/). */

package meuprojetoLFT.lexer;

import java.io.*;
import meuprojetoLFT.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeufim(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUltimofim(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeufaca(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuate(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuenquanto(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeupara(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeurepita(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariavel(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuinicio(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuprograma(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeutipo(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuregistro(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractere(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuse(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeusenao(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeucaso(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeufimSe(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeufimPara(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeufimEnquanto(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeufimRepita(line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEspacoembranco(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeusnumeros(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuatribuicao(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeufimLinha(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuParentEsq(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuParentDir(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuColcheEsq(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuColcheDir(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeudoispontos(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeumais(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeumenos(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeumultiplicacao(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeudivisao(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeumenorque(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeumenorigual(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeumaiorque(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeumaiorigual(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMeuigual(line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{32, 32, 1}, {40, 40, 2}, {41, 41, 3}, {42, 42, 4}, {43, 43, 5}, {45, 45, 6}, {47, 47, 7}, {48, 57, 8}, {58, 58, 9}, {59, 59, 10}, {60, 60, 11}, {61, 61, 12}, {62, 62, 13}, {65, 90, 14}, {91, 91, 15}, {93, 93, 16}, {95, 95, 17}, {97, 97, 18}, {98, 98, 14}, {99, 99, 19}, {100, 100, 14}, {101, 101, 20}, {102, 102, 21}, {103, 104, 14}, {105, 105, 22}, {106, 111, 14}, {112, 112, 23}, {113, 113, 14}, {114, 114, 24}, {115, 115, 25}, {116, 116, 26}, {117, 117, 14}, {118, 118, 27}, {119, 122, 14}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 8}, {65, 90, 28}, {97, 122, 28}, },
            {{61, 61, 29}, },
            {},
            {{61, 61, 30}, },
            {},
            {{61, 61, 31}, },
            {{48, 57, 32}, {65, 90, 14}, {95, 95, 33}, {97, 122, 14}, },
            {},
            {},
            {{48, 57, 34}, {65, 90, 35}, {95, 95, 36}, {97, 122, 35}, },
            {{48, 95, -16}, {97, 115, 14}, {116, 116, 37}, {117, 122, 14}, },
            {{48, 95, -16}, {97, 97, 38}, {98, 122, 14}, },
            {{48, 95, -16}, {97, 109, 14}, {110, 110, 39}, {111, 122, 14}, },
            {{48, 95, -16}, {97, 97, 40}, {98, 104, 14}, {105, 105, 41}, {106, 122, 14}, },
            {{48, 109, -22}, {110, 110, 42}, {111, 122, 14}, },
            {{48, 95, -16}, {97, 97, 43}, {98, 113, 14}, {114, 114, 44}, {115, 122, 14}, },
            {{48, 95, -16}, {97, 100, 14}, {101, 101, 45}, {102, 122, 14}, },
            {{48, 100, -26}, {101, 101, 46}, {102, 122, 14}, },
            {{48, 95, -16}, {97, 104, 14}, {105, 105, 47}, {106, 122, 14}, },
            {{48, 95, -16}, {97, 97, 48}, {98, 122, 14}, },
            {{48, 57, 49}, {65, 90, 50}, {95, 95, 51}, {97, 122, 50}, },
            {},
            {},
            {},
            {{48, 57, 52}, {65, 90, 53}, {95, 95, 54}, {97, 122, 53}, },
            {{95, 95, 33}, },
            {{48, 57, 34}, {65, 90, 55}, {95, 95, 56}, {97, 122, 55}, },
            {{48, 57, 57}, {65, 90, 35}, {95, 95, 58}, {97, 122, 35}, },
            {{48, 57, 59}, {65, 90, 60}, {95, 95, 36}, {97, 122, 60}, },
            {{48, 100, -26}, {101, 101, 61}, {102, 122, 14}, },
            {{48, 95, -16}, {97, 113, 14}, {114, 114, 62}, {115, 115, 63}, {116, 122, 14}, },
            {{48, 95, -16}, {97, 112, 14}, {113, 113, 64}, {114, 122, 14}, },
            {{48, 95, -16}, {97, 98, 14}, {99, 99, 65}, {100, 122, 14}, },
            {{48, 95, -16}, {97, 108, 14}, {109, 109, 66}, {110, 122, 14}, },
            {{48, 104, -28}, {105, 105, 67}, {106, 115, 14}, {116, 116, 68}, {117, 122, 14}, },
            {{48, 113, -40}, {114, 114, 69}, {115, 122, 14}, },
            {{48, 95, -16}, {97, 110, 14}, {111, 111, 70}, {112, 122, 14}, },
            {{48, 95, -16}, {97, 97, 71}, {98, 102, 14}, {103, 103, 72}, {104, 111, 14}, {112, 112, 73}, {113, 122, 14}, },
            {{48, 109, -22}, {110, 110, 74}, {111, 122, 14}, },
            {{48, 95, -16}, {97, 111, 14}, {112, 112, 75}, {113, 122, 14}, },
            {{48, 113, -40}, {114, 114, 76}, {115, 122, 14}, },
            {{48, 57, 49}, {65, 122, -10}, },
            {{48, 57, 77}, {65, 122, -30}, },
            {{95, 95, 51}, },
            {{48, 57, 52}, {65, 90, 50}, {95, 95, 54}, {97, 122, 50}, },
            {{48, 57, 78}, {65, 90, 53}, {97, 122, 53}, },
            {{95, 95, 54}, },
            {{48, 57, 79}, {65, 90, 80}, {95, 95, 81}, {97, 122, 80}, },
            {{95, 95, 56}, },
            {{48, 57, 82}, {65, 90, 83}, {95, 95, 84}, {97, 122, 83}, },
            {{95, 95, 58}, },
            {{48, 57, 59}, {65, 90, 85}, {95, 95, 56}, {97, 122, 85}, },
            {{48, 57, 86}, {65, 90, 60}, {95, 95, 87}, {97, 122, 60}, },
            {{48, 122, -16}, },
            {{48, 95, -16}, {97, 97, 88}, {98, 122, 14}, },
            {{48, 110, -46}, {111, 111, 89}, {112, 122, 14}, },
            {{48, 95, -16}, {97, 116, 14}, {117, 117, 90}, {118, 122, 14}, },
            {{48, 95, -16}, {97, 97, 91}, {98, 122, 14}, },
            {{32, 32, 92}, {46, 46, 93}, {48, 122, -16}, },
            {{48, 98, -42}, {99, 99, 94}, {100, 122, 14}, },
            {{48, 100, -26}, {101, 101, 95}, {102, 122, 14}, },
            {{48, 95, -16}, {97, 97, 96}, {98, 122, 14}, },
            {{48, 95, -16}, {97, 102, 14}, {103, 103, 97}, {104, 122, 14}, },
            {{48, 95, -16}, {97, 107, 14}, {108, 108, 98}, {109, 122, 14}, },
            {{48, 104, -28}, {105, 105, 99}, {106, 122, 14}, },
            {{48, 104, -28}, {105, 105, 100}, {106, 122, 14}, },
            {{48, 95, -16}, {97, 97, 101}, {98, 122, 14}, },
            {{48, 110, -46}, {111, 111, 102}, {112, 122, 14}, },
            {{48, 122, -16}, },
            {{48, 122, -52}, },
            {{48, 57, 77}, {65, 90, 53}, {95, 95, 51}, {97, 122, 53}, },
            {{48, 57, 79}, {65, 90, 103}, {97, 122, 103}, },
            {{48, 57, 104}, {65, 122, -57}, },
            {{95, 95, 81}, },
            {{48, 57, 82}, {65, 90, 105}, {95, 95, 84}, {97, 122, 105}, },
            {{48, 57, 106}, {65, 90, 83}, {97, 122, 83}, },
            {{95, 95, 84}, },
            {{48, 57, 107}, {65, 90, 108}, {95, 95, 109}, {97, 122, 108}, },
            {{48, 57, 110}, {65, 90, 111}, {95, 95, 112}, {97, 122, 111}, },
            {{95, 95, 87}, },
            {{48, 98, -42}, {99, 99, 113}, {100, 122, 14}, },
            {{48, 122, -16}, },
            {{48, 95, -16}, {97, 97, 114}, {98, 122, 14}, },
            {{48, 122, -16}, },
            {{101, 101, 115}, {112, 112, 116}, {114, 114, 117}, {115, 115, 118}, },
            {},
            {{48, 104, -28}, {105, 105, 119}, {106, 122, 14}, },
            {{48, 104, -28}, {105, 105, 120}, {106, 122, 14}, },
            {{48, 122, -16}, },
            {{48, 113, -40}, {114, 114, 121}, {115, 122, 14}, },
            {{48, 122, -16}, },
            {{48, 95, -16}, {97, 114, 14}, {115, 115, 122}, {116, 122, 14}, },
            {{48, 115, -20}, {116, 116, 123}, {117, 122, 14}, },
            {{48, 110, -46}, {111, 111, 124}, {112, 122, 14}, },
            {{48, 122, -16}, },
            {{48, 57, 79}, {65, 90, 105}, {95, 95, 125}, {97, 122, 105}, },
            {{48, 57, 104}, {65, 122, -105}, },
            {{48, 122, -106}, },
            {{48, 57, 104}, {65, 90, 83}, {95, 95, 125}, {97, 122, 83}, },
            {{48, 57, 107}, {65, 90, 126}, {97, 122, 126}, },
            {{48, 57, 127}, {65, 122, -87}, },
            {{95, 95, 109}, },
            {{48, 57, 110}, {65, 90, 128}, {95, 95, 112}, {97, 122, 128}, },
            {{48, 57, 129}, {65, 90, 111}, {97, 122, 111}, },
            {{95, 95, 112}, },
            {{48, 115, -20}, {116, 116, 130}, {117, 122, 14}, },
            {{48, 109, -22}, {110, 110, 131}, {111, 122, 14}, },
            {{110, 110, 132}, },
            {{97, 97, 133}, },
            {{101, 101, 134}, },
            {{101, 101, 135}, },
            {{48, 110, -46}, {111, 111, 136}, {112, 122, 14}, },
            {{48, 113, -40}, {114, 114, 137}, {115, 122, 14}, },
            {{48, 95, -16}, {97, 97, 138}, {98, 122, 14}, },
            {{48, 115, -20}, {116, 116, 139}, {117, 122, 14}, },
            {{48, 95, -16}, {97, 97, 140}, {98, 122, 14}, },
            {{48, 122, -16}, },
            {{95, 95, 125}, },
            {{48, 57, 107}, {65, 90, 128}, {95, 95, 141}, {97, 122, 128}, },
            {{48, 57, 127}, {65, 122, -128}, },
            {{48, 122, -129}, },
            {{48, 57, 127}, {65, 90, 111}, {95, 95, 141}, {97, 122, 111}, },
            {{48, 100, -26}, {101, 101, 142}, {102, 122, 14}, },
            {{48, 115, -20}, {116, 116, 143}, {117, 122, 14}, },
            {{113, 113, 144}, },
            {{114, 114, 145}, },
            {{112, 112, 146}, },
            {},
            {{48, 122, -16}, },
            {{48, 110, -46}, {111, 111, 147}, {112, 122, 14}, },
            {{48, 108, -43}, {109, 109, 148}, {110, 122, 14}, },
            {{48, 113, -40}, {114, 114, 149}, {115, 122, 14}, },
            {{48, 122, -16}, },
            {{95, 95, 141}, },
            {{48, 113, -40}, {114, 114, 150}, {115, 122, 14}, },
            {{48, 110, -46}, {111, 111, 151}, {112, 122, 14}, },
            {{117, 117, 152}, },
            {{97, 97, 153}, },
            {{105, 105, 154}, },
            {{48, 122, -16}, },
            {{48, 95, -16}, {97, 97, 155}, {98, 122, 14}, },
            {{48, 110, -46}, {111, 111, 156}, {112, 122, 14}, },
            {{48, 100, -26}, {101, 101, 157}, {102, 122, 14}, },
            {{48, 122, -16}, },
            {{97, 97, 158}, },
            {},
            {{116, 116, 159}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{48, 122, -16}, },
            {{110, 110, 160}, },
            {{97, 97, 161}, },
            {{116, 116, 162}, },
            {},
            {{111, 111, 163}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 22, 26, 27, 33, 31, 32, 34, 23, 30, 25, 35, 39, 37, 40, 28, 29, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 24, 36, 38, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 15, 40, 40, -1, 40, 40, 40, -1, 40, 40, 40, 40, 40, 40, 40, 3, 40, 40, 40, 40, 0, 40, 40, 40, 40, 40, 40, 40, 40, 40, 7, 40, 40, -1, 40, 40, 40, -1, 40, 40, 40, 40, 40, 17, 40, 2, -1, 1, 40, 40, 5, 40, 12, 40, 40, 40, 10, 40, 40, 40, 40, -1, 40, 40, 40, -1, 40, 40, 40, -1, -1, -1, -1, 40, 40, 40, 40, 40, 16, 40, 40, 40, 40, 40, 40, 40, -1, -1, -1, 18, 8, 40, 40, 40, 6, 40, 40, 40, -1, -1, -1, 13, 40, 40, 40, 4, -1, 19, -1, 9, 11, 14, -1, -1, -1, 21, -1, 20, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
